; Zeile 0–3 × Spalte 0–11 = 48 Tasten (0–47)
; Block 1: HEX  | Block 2: Navigation | Block 3: Makros & Tools

key_ascii_table:
    ; Zeile 0
    .byte "0","1","2","3",   "^","O","E","D",   "M","N","P","Q"
    ; Zeile 1
    .byte "4","5","6","7",   "<",13 ,27 ,127,   "C","I","G","L"
    ; Zeile 2
    .byte "8","9","A","B",   "v",9 , 22 ,25 ,   "X","Y","Z","W"
    ; Zeile 3
    .byte "C","D","E","F",   "~","S","R"," ",   "[","]", 8 ,10